name: Deploy Active Directory DCs to Azure

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Select the target server"
        required: true
        type: choice
        options:
          - DC01
          - DC02

      terraform_task:
        description: "Select the Terraform task to run"
        required: true
        type: choice
        options:
          - none
          - plan
          - apply
          - destroy

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_AZUREAD: true
  ARM_SKIP_PROVIDER_REGISTRATION: false

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.terraform_task }}
    if: github.event.inputs.terraform_task != 'none'
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/ad-deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}"

      - name: Terraform Plan
        id: plan
        if: github.event.inputs.terraform_task == 'plan' || github.event.inputs.terraform_task == 'apply'
        run: |
          terraform plan -out main.tfplan -detailed-exitcode || {
            exitcode=$?
            if [ $exitcode -eq 1 ]; then
              echo "Terraform plan failed"
              exit 1
            else
              echo "Terraform plan was successful"
            fi
          }

      - name: Terraform Apply
        if: github.event.inputs.terraform_task == 'apply' && steps.plan.outcome == 'success'
        run: terraform apply -auto-approve "main.tfplan"
